#pragma once

//#define OSRBUDDY_DEBUG
//#define OSRBUDDY_MANUALMAP

//#define SUMMER_EVENT
//#define HALLOWEEN_EVENT
#define CHRISTMAS_EVENT


#ifdef 	RELEASE_EXTERNAL
	#define FEATURE_ENCHANTBOT
	#define FEATURE_GAMBLEBOT
	#define FEATURE_FACTORYBOT
#elif defined RELEASE_FULL || defined RELEASE_SETHIA // all features
	#define FEATURE_ENCHANTBOT
	#define FEATURE_GAMBLEBOT
	#define FEATURE_GRINDBOT
	#define FEATURE_KITBOT
	#define FEATURE_MISCELLANEOUS
	#define FEATURE_INVENTORYMANAGER
	#define FEATURE_FACTORYBOT
#endif

#ifdef RELEASE_DEBUG		
	#define FEATURE_ENCHANTBOT
	#define FEATURE_GAMBLEBOT
	#define FEATURE_GRINDBOT
	#define FEATURE_KITBOT
	#define FEATURE_MISCELLANEOUS
	#define FEATURE_INVENTORYMANAGER
	#define FEATURE_FACTORYBOT
	#define OSRBUDDY_DEBUG
	#define	FEATURE_ESP
	#define FEATURE_TEST
#endif

#ifdef OSRBUDDY_MANUALMAP
#define BUDDY_EXPORTS
#endif

//#define OSRBUDDY_DEBUG
#define FEATURE_ANTIRAND  