#pragma once

//#define SUMMER_EVENT
#define HALLOWEEN_EVENT


#define FEATURE_ENCHANTBOT
#define FEATURE_GAMBLEBOT
#define FEATURE_GRINDBOT
#define FEATURE_KITBOT
#define FEATURE_MISCELLANEOUS
#define FEATURE_INVENTORYMANAGER

#ifdef RELEASE_DEBUG
	#define FEATURE_FACTORYBOT
	#define FEATURE_TEST
	//#define FEATURE_VISUALS
#endif

