#pragma once

#define OSRBUDDY_DEBUG
//#define OSRBUDDY_MANUALMAP



//#define SUMMER_EVENT
#define HALLOWEEN_EVENT


#define FEATURE_ENCHANTBOT
#define FEATURE_GAMBLEBOT
#define FEATURE_GRINDBOT
#define FEATURE_KITBOT
#define FEATURE_MISCELLANEOUS
#define FEATURE_INVENTORYMANAGER

#ifdef RELEASE_DEBUG
	//#define FEATURE_FACTORYBOT
	#define FEATURE_TEST
	#define OSRBUDDY_DEBUG
#endif

#ifdef OSRBUDDY_DEBUG
#define FEATURE_DEBUGINFO
#endif

#ifdef OSRBUDDY_MANUALMAP
#define BUDDY_EXPORTS
#endif